debug: debug

#端口
server:
  port: 8080

spring:
  application:
    name: springboot-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT
    username: root    # 用户名
    password: root    # 密码
    initialSize: 5    # 指定启动连接池时，初始建立的连接数量
    minIdle: 5        # 指定必须保持连接的最小值
    maxActive: 20     # 指定连接池中最大的活跃连接数.
    maxWait: 60000    # 指定连接池等待连接返回的最大等待时间，单位毫秒.
    timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
    validationQuery: SELECT 1       # 配置一个连接在池中最小生存的时间，单位是毫秒
    testWhileIdle: true             # 当连接空闲时，是否进行有效性验证(即是否还和数据库连通)
    testOnBorrow: false             # 当取得连接时，是否进行有效性验证
    testOnReturn: false             # 当返回连接时，是否进行有效性验证
    poolPreparedStatements: true    # 打开PSCache
    maxPoolPreparedStatementPerConnectionSiz: 20    # 指定每个连接上PSCache的大小
    filters: stat,wall,log4j    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

# mybatis
mybatis:
  configuration:
    # 配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true
  # 指定实体类bean所在包
#  type-aliases-package: com.example.entity

# 通用Mapper
mapper:
  # 公用接口类路径
  mappers: com.example.utils.BaseMapper
  # 如果不使用纯注解方式需配置mapper接口对应的.xml文件地址
  mapper-locations: classpath:mapper/*.xml
  notEmpty: false
  identity: MYSQL

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# url
url:
  # 百度
  baidu: https://www.baidu.com
